import React, { useEffect, useState } from 'react'
import { api, download, unwrap } from '../api'
import { Button, Card, ErrorBox, Input, Modal, PageHeader, Select, Textarea, money, today } from '../components/Ui'

export default function PaymentsPage({ currency='AED' }){
 const [rows,setRows]=useState([]),[customers,setCustomers]=useState([]),[suppliers,setSuppliers]=useState([]),[error,setError]=useState(''),[open,setOpen]=useState(false)
 const [form,setForm]=useState({party_type:'CUSTOMER',customer:'',supplier:'',date:today(),amount:'',payment_method:'CASH',reference:'',notes:''})
 async function load(){try{const [p,c,s]=await Promise.all([api('/payments/?page_size=100'),api('/customers/?page_size=100'),api('/suppliers/?page_size=100')]);setRows(unwrap(p));setCustomers(unwrap(c));setSuppliers(unwrap(s))}catch(e){setError(e.message)}}
 useEffect(()=>{load()},[])
 async function save(e){e.preventDefault();try{const body={...form,customer:form.party_type==='CUSTOMER'&&form.customer?Number(form.customer):null,supplier:form.party_type==='SUPPLIER'&&form.supplier?Number(form.supplier):null};await api('/payments/',{method:'POST',body});setOpen(false);await load()}catch(e){setError(e.message)}}
 return <><PageHeader title="Payments" subtitle="Customer receipts and supplier payments" actions={<Button onClick={()=>setOpen(true)}>+ Record Payment</Button>}/><ErrorBox error={error}/><Card><div className="table-wrap"><table><thead><tr><th>Receipt</th><th>Date</th><th>Type</th><th>Party</th><th>Method</th><th>Amount</th><th>Reference</th><th/></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.receipt_no}</td><td>{r.date}</td><td>{r.party_type}</td><td>{r.customer_name||r.supplier_name||'-'}</td><td>{r.payment_method}</td><td>{money(r.amount,currency)}</td><td>{r.reference||'-'}</td><td><button onClick={()=>download(`/payments/${r.id}/receipt_pdf/`,`${r.receipt_no}.pdf`)}>PDF</button></td></tr>)}</tbody></table></div></Card>
 <Modal open={open} title="Record Payment" onClose={()=>setOpen(false)}><form onSubmit={save}><Select label="Payment Type" value={form.party_type} onChange={e=>setForm({...form,party_type:e.target.value,customer:'',supplier:''})}><option value="CUSTOMER">Customer Receipt</option><option value="SUPPLIER">Supplier Payment</option></Select>{form.party_type==='CUSTOMER'?<Select label="Customer" required value={form.customer} onChange={e=>setForm({...form,customer:e.target.value})}><option value="">Select customer</option>{customers.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select>:<Select label="Supplier" required value={form.supplier} onChange={e=>setForm({...form,supplier:e.target.value})}><option value="">Select supplier</option>{suppliers.map(x=><option key={x.id} value={x.id}>{x.code} — {x.name}</option>)}</Select>}<Input label="Date" type="date" required value={form.date} onChange={e=>setForm({...form,date:e.target.value})}/><Input label="Amount" type="number" min="0.01" step="0.01" required value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/><Select label="Method" value={form.payment_method} onChange={e=>setForm({...form,payment_method:e.target.value})}><option value="CASH">Cash</option><option value="BANK">Bank Transfer</option><option value="CARD">Card</option><option value="CHEQUE">Cheque</option><option value="OTHER">Other</option></Select><Input label="Reference" value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/><Textarea label="Notes" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="modal-actions"><Button type="button" variant="ghost" onClick={()=>setOpen(false)}>Cancel</Button><Button>Save Payment</Button></div></form></Modal></>
}
