import React, { useEffect, useState } from 'react'
import { api } from '../api'
import { Button, Card, ErrorBox, Input, PageHeader, Select, Textarea } from '../components/Ui'

export default function SettingsPage({ onChanged }){
 const [form,setForm]=useState(null),[error,setError]=useState(''),[saved,setSaved]=useState(false)
 useEffect(()=>{api('/settings/').then(setForm).catch(e=>setError(e.message))},[])
 async function save(e){e.preventDefault();setSaved(false);try{const data=await api('/settings/',{method:'PUT',body:form});setForm(data);setSaved(true);onChanged?.(data)}catch(e){setError(e.message)}}
 if(!form)return <><PageHeader title="Settings"/><div className="loading">Loading…</div></>
 return <><PageHeader title="Settings" subtitle="Company, currency, VAT, invoice and bank configuration"/><ErrorBox error={error}/>{saved&&<div className="success-box">Settings saved.</div>}<form onSubmit={save}><Card><h3>Company</h3><div className="form-grid"><Input label="Company Name" value={form.company_name} onChange={e=>setForm({...form,company_name:e.target.value})}/><Input label="Phone" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/><Input label="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><Input label="TRN / Tax No" value={form.trn} onChange={e=>setForm({...form,trn:e.target.value})}/><Textarea label="Address" value={form.address} onChange={e=>setForm({...form,address:e.target.value})}/></div></Card><Card><h3>Currency & Tax</h3><div className="form-grid"><Select label="Currency Code" value={form.currency_code} onChange={e=>setForm({...form,currency_code:e.target.value,currency_symbol:e.target.value==='USD'?'$':e.target.value})}><option>AED</option><option>USD</option><option>PKR</option><option>SAR</option><option>EUR</option><option>GBP</option></Select><Input label="Currency Symbol" value={form.currency_symbol} onChange={e=>setForm({...form,currency_symbol:e.target.value})}/><Input label="Default VAT %" type="number" step="0.01" value={form.default_vat} onChange={e=>setForm({...form,default_vat:e.target.value})}/></div></Card><Card><h3>Document Numbers</h3><div className="form-grid"><Input label="Invoice Prefix" value={form.invoice_prefix} onChange={e=>setForm({...form,invoice_prefix:e.target.value})}/><Input label="Purchase Prefix" value={form.purchase_prefix} onChange={e=>setForm({...form,purchase_prefix:e.target.value})}/><Input label="Receipt Prefix" value={form.receipt_prefix} onChange={e=>setForm({...form,receipt_prefix:e.target.value})}/><Textarea label="Invoice Terms" value={form.terms} onChange={e=>setForm({...form,terms:e.target.value})}/></div></Card><Card><h3>Bank Details</h3><div className="form-grid"><Input label="Bank Name" value={form.bank_name} onChange={e=>setForm({...form,bank_name:e.target.value})}/><Input label="Account Title" value={form.account_title} onChange={e=>setForm({...form,account_title:e.target.value})}/><Input label="Account Number" value={form.account_number} onChange={e=>setForm({...form,account_number:e.target.value})}/><Input label="IBAN" value={form.iban} onChange={e=>setForm({...form,iban:e.target.value})}/></div></Card><div className="save-bar"><Button>Save Settings</Button></div></form></>
}
