# Generated by Django 5.2.15 on 2026-08-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysetting',
            name='company_name',
            field=models.CharField(default='Shinwari Electronics and Decoration', max_length=180),
        ),
    ]
